import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"], // Load only Latin characters
  weight: ["400", "700"], // Regular & Bold
  style: ["normal", "italic"], // Normal & Italic styles
  display: "swap", // Ensures faster font rendering
  variable: "--font-roboto", // Custom CSS variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>{children}</body>
    </html>
  );
}
